### ISSUE TITLE
Copywrite - Step 00 of Typography article

### ISSUE THREAD

**Issue by smiska** [EDMdesigner/modern-html-email-tutorial#127]

**Comment by smiska** [comment]
http://blog.edmdesigner.com/p/c7dca05b-6ef8-4f02-bc02-6a16995df4d2/#defaulttextrelatedtagsinemailhtml

**Comment by gyulanemeth** [comment]
- Sejtelmem sincs, hogy ez a mondat mit jelent: It gives our template semantic meaning, which means that the HTML tag describes the role of its content.

	- mindenféle tagről beszélsz itt, viszont a példában olyan is van, ami nincs megemlítve. (ul, ol)

	- Strong, b, em, i, cite, blockquote, q and pre are called phrase tags. --- ez az infó miért fontos nekem? fogod használni ezt a kifejezést?

	- nem lehet, hogy jobb lenne egy táblázat az itteni leírás helyett?

	- There are still many email clients, that do not support styles, if they are put inside style tags. -- nem túl szerencsés ez a mondat + that előtt nincs veszső, ahogy múlt órán is tanultuk

	- tök invalidnak hangzik a kontextus alapján ez a mondat: They inherit font-size 0px from body.
		- amúgy from the body

	- ez jó mondat?  This results in different looks:
