### ISSUE TITLE
Yesmail colors

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/modern-html-email-tutorial#150]
Title color: #54b948 
Text color: black (#000000) 
Body background color: #ffffff 
Dominant color: #54b948 
Box background color: #efeff0
Box header color: #efeff0 
Box text color: #000000

**Comment by balintsoos** [comment]
this issue moved to: https://github.com/EDMdesigner/EDMdesigner-API-Client/issues/105
